name=input("enter your name")
dateofbirth=input("enter your date of birth")
email=input("enter your email id")
mobile=input("enter mob number")
place=input("enter your place")
pincode=input("enter your pincode")
username=input("enter your username")
password=input("enter password")
confirmpassword=input("enter password")
if(password==confirmpassword):
    print(name)
    print(dateofbirth)
    print(email)
    print(mobile)
    print(place)
    print(pincode)
    print(username)
    print(password)
    print(confirmpassword)
else:
    print("password and confirm password doesn't match")